tabs:
    fields:
        name:
            label: Name
            span: left
            type: text
            tab: General

        logo:
            label: Logo
            span: right
            type: fileupload
            tab: General

        section_auth:
            label: Authentication
            span: full
            type: section
            tab: Features

        login_required:
            label: Login required
            span: left
            type: switch
            default: false
            tab: Features

        allow_registration:
            label: Allow registration
            span: left
            type: switch
            default: true
            tab: Features

        section_layout:
            label: Layout
            span: full
            type: section
            tab: Features

        show_footer:
            label: Show footer
            span: left
            type: switch
            default: true
            tab: Features

        show_branding_on_login_page:
            label: Show branding on login page
            span: left
            type: switch
            default: false
            tab: Features

        course_sidebar:
            label: Show course sidebar
            span: left
            type: switch
            tab: Features

        show_new_course_badge:
            label: Show new course badge
            span: left
            type: switch
            tab: Features

        new_course_day_count:
            label: New course day count
            span: right
            type: number
            tab: Features
            trigger:
                action: show
                field: show_new_course_badge
                condition: checked

        custom_css:
            label: Custom CSS
            span: full
            type: codeeditor
            size: giant
            tab: Custom CSS
            language: css
            showGutter: true

        show_announcement:
            label: Show announcement
            span: left
            default: false
            type: switch
            tab: Announcement

        announcement_type:
            label: Type
            span: left
            type: dropdown
            tab: Announcement
            options:
                info: Information
                warning: Warning
                error: Error
                success: Success

        announcement_title:
            label: Title
            span: left
            type: text
            tab: Announcement

        announcement:
            label: Announcement
            tab: Announcement
            span: left
            type: textarea


