tabs:
    fields:
        name:
            label: Name
            span: left
            type: text
            tab: General

        logo:
            label: Logo
            span: right
            type: fileupload
            tab: General

        course_sidebar:
            label: Show course sidebar
            span: left
            type: switch
            tab: Features

        show_new_course_badge:
            label: Show new course badge
            span: left
            type: switch
            tab: Features

        new_course_day_count:
            label: New course day count
            span: left
            type: number
            tab: Features
            trigger:
                action: show
                field: show_new_course_badge
                condition: checked

        custom_css:
            label: Custom CSS
            span: full
            type: codeeditor
            size: giant
            tab: Custom CSS
            language: css
            showGutter: true

        show_announcement:
            label: Show announcement
            span: left
            default: false
            type: switch
            tab: Announcement

        announcement_type:
            label: Type
            span: left
            type: dropdown
            tab: Announcement
            options:
                info: Information
                warning: Warning
                error: Error
                success: Success

        announcement_title:
            label: Title
            span: left
            type: text
            tab: Announcement

        announcement:
            label: Announcement
            tab: Announcement
            span: left
            type: textarea


