# This is a basic workflow to help you get started with Actions

name: 'Deploy on push'

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ploi-deploy:
    # The type of runner that the job will run on
    name: 'Ploi Deploy'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Deploy
        uses: Glennmen/ploi-deploy-action@v1.1.0
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
